const characters = [
	// Richness
	{
		name: 'Marc Sugarberg',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card34.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Tom Kook',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card24.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Steve Jops',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card18.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Bill Mates',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card31.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Larry Sage',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card11.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Sergey Green',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card28.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Sam Aitman',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card35.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Vitaly Bulletin',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card04.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{
		name: 'Margo Robo',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card38.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#0fff0f',
	},
	{ name: 'Tyler Sweeft', characteristic: 'Richness' },

	// Popularity
	{
		name: 'Povel Durev',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card23.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Satoshi Hellomoto',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card03.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Jackie Chwan',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card26.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Lion Messiah',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card13.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'LebrOne James',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card17.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Hack Ma',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card16.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Buff Warrant',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card27.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{
		name: 'Michael BloomBig',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card30.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#9c40ff',
		colorFrom: '#ffff0f',
	},
	{ name: 'Donna Gaga', characteristic: 'Popularity' },
	{ name: 'Zandaia', characteristic: 'Popularity' },

	// Attractiveness
	{
		name: 'Patrick Makhomes',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card14.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Elan Mosk',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card01.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Billie Stylish',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card22.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Charleez Tiron',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card25.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Ariadna Grant',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card33.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Selene Gomes',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card07.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Irina Shake',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card19.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Ursula Fonder Line',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card05.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Kim Kong-fun',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card02.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},
	{
		name: 'Jeff Besos',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card36.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#9c40ff',
		colorFrom: '#0ffcff',
	},

	// Dominion
	{
		name: 'Scarlit Yohansen',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card08.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{ name: 'Buyonce', characteristic: 'Dominion' },
	{
		name: 'Christian Penaldo',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card09.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Tim Brody',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card29.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Madronna',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card15.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Divine Johnzon',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card37.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Papa Frank',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card20.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Opra Winfred',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card12.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Steven Kong',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card06.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Chaquira',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card32.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Emma Vatson',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card21.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
	{
		name: 'Ri Anna',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card10.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#9c40ff',
		colorFrom: '#ff0f0f',
	},
];

export default characters;
