const characters = [
	// Richness
	{
		number: "001",
		
		name: 'Marc Sugarberg',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card34.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "002",
		
		name: 'Tom Kook',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card24.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "003",
		
		name: 'Steve Jops',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card18.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "004",
			
		name: 'Bill Mates',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card31.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "005",
		
		name: 'Larry Sage',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card11.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "006",
			
		name: 'Sergey Green',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card28.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "007",
		
		name: 'Sam Aitman',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card35.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "008",
		name: 'Vitaly Bulletin',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card04.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "009",
		name: 'Margo Robo',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card38.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#080E4C',
		colorFrom: '#0fff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	//{ name: 'Tyler Sweeft', characteristic: 'Richness' },

	// Popularity
	{
		number: "010",
		name: 'Povel Durev',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card23.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "011",
		name: 'Satoshi Hellomoto',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card03.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "012",
		name: 'Jackie Chwan',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card26.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "013",
		name: 'Lion Messiah',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card13.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "014",
		name: 'LebrOne James',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card17.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "015",
		name: 'Hack Ma',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card16.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "016",
		name: 'Buff Warrant',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card27.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "017",
		name: 'Michael BloomBig',
		characteristic: 'Popularity',
		srcFront: '/characters/middle/card30.png',
		altFront: 'Popularity character',
		altBack: 'Popularity character',
		colorTo: '#080E4C',
		colorFrom: '#ffff0f',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	//{ name: 'Donna Gaga', characteristic: 'Popularity' },
	//{ name: 'Zandaia', characteristic: 'Popularity' },

	// Attractiveness
	{
		number: "018",
		name: 'Patrick Makhomes',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card14.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "019",
		name: 'Elan Mosk',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card01.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "020",
		name: 'Billie Stylish',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card22.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "021",
		name: 'Charleez Tiron',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card25.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "022",
		name: 'Ariadna Grant',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card33.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "023",
		name: 'Selene Gomes',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card07.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "024",
		name: 'Irina Shake',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card19.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "025",
		name: 'Ursula Fonder Line',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card05.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "026",
		name: 'Kim Kong-fun',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card02.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "027",
		name: 'Jeff Besos',
		characteristic: 'Attractiveness',
		srcFront: '/characters/middle/card36.png',
		altFront: 'Attractiveness character',
		altBack: 'Attractiveness character',
		colorTo: '#080E4C',
		colorFrom: '#0ffcff',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},

	// Dominion
	{
		number: "028",
		name: 'Scarlit Yohansen',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card08.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	//{ name: 'Buyonce', characteristic: 'Dominion' },
	{
		number: "029",
		name: 'Christian Penaldo',
		characteristic: 'Richness',
		srcFront: '/characters/middle/card09.png',
		altFront: 'Richness character',
		altBack: 'Richness character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "030",
		name: 'Tim Brody',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card29.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "031",
		name: 'Madronna',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card15.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "032",
		name: 'Divine Johnzon',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card37.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "033",
		name: 'Papa Frank',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card20.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "034",
		name: 'Opra Winfred',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card12.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "035",
		name: 'Steven Kong',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card06.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "036",
		name: 'Chaquira',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card32.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "037",
		name: 'Emma Vatson',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card21.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
	{
		number: "038",
		name: 'Ri Anna',
		characteristic: 'Dominion',
		srcFront: '/characters/middle/card10.png',
		altFront: 'Dominion character',
		altBack: 'Dominion character',
		colorTo: '#ff0f0f',
		colorFrom: '#080E4C',
		username: '@durev',
		body: "I'm glad the game works on Telegram",
	},
];

export default characters;
